services:
  mysql:
    image: 'mysql:8.0.37'
    environment:
      - 'MYSQL_DATABASE=hiss_db'
      - 'MYSQL_PASSWORD=!Qwer432'
      - 'MYSQL_ROOT_PASSWORD=!Qwer432'
      - 'MYSQL_USER=hiss'
    volumes:
      - ./hiss_db.sql:/docker-entrypoint-initdb.d/hiss_db.sql
    ports:
      - '3306'
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - '8080:8080'
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - 'PORT=8080'
      - 'SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/hiss_db'
      - 'SPRING_DATASOURCE_USERNAME=hiss'
      - 'SPRING_DATASOURCE_PASSWORD=!Qwer432'
      - 'ADMIN_PASSWORD=!Qwer432'
      - 'JPA_DATABASE=mysql'
      - 'JPA_DATABASE_PLATFORM=org.hibernate.dialect.MySQL8Dialect'
      - 'SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver'